cc=gcc

all:
	$(cc) cat.c -o cat
	$(cc) copy.c -o copy
	$(cc) crdir.c -o crdir
	$(cc) del.c -o del
	$(cc) deldir.c -o deldir
	$(cc) echo.c -o echo
	$(cc) help.c -o help
	$(cc) ls.c -o ls
	$(cc) ls\ -all.c -o ls\ -all
	$(cc) ls\ -tree.c -o ls\ -tree
	$(cc) touch.c -o touch
	
rem:
	rm ./cat
	rm ./copy
	rm ./crdir
	rm ./del
	rm ./deldir
	rm ./echo
	rm ./help
	rm ./ls
	rm ./ls\ -all
	rm ./ls\ -tree
	rm ./touch

